cmake_minimum_required(VERSION 3.22)

project(Motivator VERSION 0.1.0)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(SMTG_RUN_VST_VALIDATOR OFF CACHE BOOL "Run the VST3 validator after building plugins" FORCE)

include(FetchContent)

FetchContent_Declare(vst3sdk
    GIT_REPOSITORY https://github.com/steinbergmedia/vst3sdk.git
    GIT_TAG 3cdf9ca5d1f5b1b21e0a86832aa4abe55607bd96
)

FetchContent_MakeAvailable(vst3sdk)

add_subdirectory(src)
