#pragma once

#include "pluginterfaces/vst/vsttypes.h"
#include <array>
#include <cstddef>

namespace MotivatoratorPhrases {

struct Phrase {
    const Steinberg::Vst::TChar* de;
    const Steinberg::Vst::TChar* en;
};

// Important: every entry is a complete standalone studio comment.
// Do not build phrases by concatenating opener/core/closer fragments; that caused
// repeated fragments to carry over perceptually from one comment to the next.
inline constexpr std::array<Phrase, 80> kMotivator {{
    {STR16("Nicht anfassen! Genau so lassen!"), STR16("Don't touch it. Leave it exactly like that!")},
    {STR16("Okay ... DAS war gerade verdammt gut."), STR16("Okay ... THAT was ridiculously good.")},
    {STR16("Ich weiß nicht, was du gemacht hast. Aber mach mehr davon."), STR16("I don't know what you did. But do more of it.")},
    {STR16("Das klingt gefährlich gut."), STR16("That sounds dangerously good.")},
    {STR16("Verdammt, kannst du das gut."), STR16("Damn, you're good at this.")},
    {STR16("Du bist sooo gut!"), STR16("You're sooo good!")},
    {STR16("Das klingt fantastisch."), STR16("That sounds fantastic.")},
    {STR16("Wow. Einfach wow."), STR16("Wow. Just wow.")},
    {STR16("Du hast es drauf. Punkt."), STR16("You've got this. Period.")},
    {STR16("Das klingt verdammt professionell."), STR16("That sounds damn professional.")},
    {STR16("Heute läuft's bei dir."), STR16("You're on fire today.")},
    {STR16("Das klingt teuer. Diesmal ist das ein Kompliment."), STR16("That sounds expensive. This time that's a compliment.")},
    {STR16("Ja! Genau das meinte ich!"), STR16("Yes! That's exactly what I meant!")},
    {STR16("Speichern. Sofort. Keine Diskussion."), STR16("Save it. Now. No discussion.")},
    {STR16("Das sitzt. Finger weg."), STR16("That sits perfectly. Hands off.")},
    {STR16("Du machst mir langsam Angst."), STR16("You're starting to scare me.")},
    {STR16("Das ist unanständig gut."), STR16("That's indecently good.")},
    {STR16("Okay, jetzt wird es ernsthaft gut."), STR16("Okay, this is getting seriously good.")},
    {STR16("Das war genau die richtige Entscheidung."), STR16("That was exactly the right decision.")},
    {STR16("Mehr davon. Viel mehr davon."), STR16("More of that. A lot more of that.")},
    {STR16("Ich würde applaudieren. Mir fehlen nur die Hände."), STR16("I'd applaud. I'm just missing the hands.")},
    {STR16("Was zur Hölle war DAS denn? Nochmal!"), STR16("What the hell was THAT? Again!")},
    {STR16("So. Und jetzt bitte nichts mehr kaputtmachen."), STR16("There. Now please don't break anything.")},
    {STR16("Das funktioniert erschreckend gut."), STR16("That works frighteningly well.")},
    {STR16("Respekt. Damit habe ich nicht gerechnet."), STR16("Respect. I did not expect that.")},
    {STR16("Das hat richtig Charakter."), STR16("That has real character.")},
    {STR16("Das klingt nach einer sehr guten Idee."), STR16("That sounds like a very good idea.")},
    {STR16("Du weißt gerade ziemlich genau, was du tust."), STR16("You know exactly what you're doing right now.")},
    {STR16("Das darf so bleiben. Offiziell genehmigt."), STR16("That may stay. Officially approved.")},
    {STR16("Ich sag's ungern, aber du bist richtig gut."), STR16("I hate to say it, but you're really good.")},
    {STR16("Das hat gerade alles zusammengeklickt."), STR16("That just clicked into place.")},
    {STR16("Genau so fühlt sich richtig an."), STR16("That's exactly what right feels like.")},
    {STR16("Das ist nicht Glück. Das kannst du."), STR16("That's not luck. You can do this.")},
    {STR16("Du hast gerade Geschmack bewiesen. Schon wieder."), STR16("You just proved you have taste. Again.")},
    {STR16("Das klingt plötzlich nach fertiger Musik."), STR16("That suddenly sounds like finished music.")},
    {STR16("Ich würde nichts mehr ändern. Wirklich nichts."), STR16("I wouldn't change a thing. Seriously.")},
    {STR16("Das hat Wucht, ohne zu schreien."), STR16("That has impact without shouting.")},
    {STR16("Da ist sie. Die richtige Version."), STR16("There it is. The right version.")},
    {STR16("Ganz ehrlich: Das ist stark."), STR16("Seriously: that's strong.")},
    {STR16("Das läuft gerade verdächtig gut."), STR16("This is going suspiciously well.")},
    {STR16("Heute bist du dein eigener Glücksfall."), STR16("Today, you're your own lucky break.")},
    {STR16("Das hat genau die richtige Energie."), STR16("That has exactly the right energy.")},
    {STR16("So klingt eine Entscheidung mit Rückgrat."), STR16("That's what a decision with backbone sounds like.")},
    {STR16("Ich hab nichts zu meckern. Unheimlich."), STR16("I've got nothing to complain about. Creepy.")},
    {STR16("Du hast gerade den Raum gewonnen."), STR16("You just won the room.")},
    {STR16("Das ist so gut, ich werde misstrauisch."), STR16("That's so good I'm getting suspicious.")},
    {STR16("Mach genau da weiter."), STR16("Keep going exactly like that.")},
    {STR16("Das hat Klasse. Ja, wirklich."), STR16("That has class. Yes, really.")},
    {STR16("Das ist gerade sehr, sehr überzeugend."), STR16("That is very, very convincing right now.")},
    {STR16("Du hast den Punkt getroffen."), STR16("You nailed the point.")},
    {STR16("Das fühlt sich fertig an. Seltenes Ereignis."), STR16("That feels finished. Rare event.")},
    {STR16("Okay, ich nehme alles zurück. Das ist geil."), STR16("Okay, I take it all back. That's great.")},
    {STR16("Dein Instinkt hat heute Dienst."), STR16("Your instincts actually showed up today.")},
    {STR16("Das klingt souverän."), STR16("That sounds confident.")},
    {STR16("Das hat genau genug von allem."), STR16("That has exactly enough of everything.")},
    {STR16("Schön. Einfach schön."), STR16("Beautiful. Just beautiful.")},
    {STR16("Du hast gerade aus Chaos Musik gemacht."), STR16("You just turned chaos into music.")},
    {STR16("Das ist bemerkenswert rund."), STR16("That's remarkably well-rounded.")},
    {STR16("Ich höre gerade ziemlich wenig, was ich ändern würde."), STR16("I'm hearing very little I'd change right now.")},
    {STR16("Da stimmt verdammt viel."), STR16("A damn lot is right here.")},
    {STR16("Das ist musikalisch einfach clever."), STR16("That's simply musically clever.")},
    {STR16("Genau dafür lohnt sich das Gefummel."), STR16("That's exactly why all the tweaking is worth it.")},
    {STR16("Das Ergebnis weiß, was es will."), STR16("The result knows what it wants.")},
    {STR16("Du hast gerade richtig abgeliefert."), STR16("You seriously delivered just now.")},
    {STR16("Das hat Selbstvertrauen."), STR16("That has confidence.")},
    {STR16("Kein Witz: Das klingt richtig gut."), STR16("No joke: that sounds really good.")},
    {STR16("Das ist einer von diesen seltenen Treffern."), STR16("This is one of those rare hits.")},
    {STR16("Ja. Das gehört genau dahin."), STR16("Yes. That belongs exactly there.")},
    {STR16("Du hast gerade die richtige Tür aufgemacht."), STR16("You just opened the right door.")},
    {STR16("Das wirkt mühelos. Gemein gut."), STR16("That feels effortless. Annoyingly good.")},
    {STR16("Heute darfst du ein bisschen arrogant sein."), STR16("You're allowed to be a little arrogant today.")},
    {STR16("Das ist richtig erwachsen geworden."), STR16("That just grew up properly.")},
    {STR16("Ich hätte da nichts mehr anzufassen."), STR16("I wouldn't touch that anymore.")},
    {STR16("Das klingt, als wäre es genau so geplant gewesen."), STR16("That sounds like it was planned exactly that way.")},
    {STR16("Du bist heute unangenehm kompetent."), STR16("You're annoyingly competent today.")},
    {STR16("Das hat gerade Niveau bekommen."), STR16("That just gained some serious class.")},
    {STR16("Das trägt sich von allein."), STR16("That carries itself.")},
    {STR16("Sehr stark. Wirklich sehr stark."), STR16("Very strong. Seriously very strong.")},
    {STR16("So macht das Spaß."), STR16("Now that's fun.")},
    {STR16("Das darfst du dir ruhig selbst glauben."), STR16("You can safely believe your own hype on this one.")}
}};

inline constexpr std::array<Phrase, 80> kDemotivator {{
    {STR16("Noch ein Versuch. Bestimmt wird's diesmal Musik."), STR16("One more try. Surely it'll become music this time.")},
    {STR16("Ich hatte keine Erwartungen. Trotzdem enttäuscht."), STR16("I had no expectations. Still disappointed.")},
    {STR16("Speicher das ruhig. Die Polizei braucht Beweise."), STR16("Go ahead and save it. The police will need evidence.")},
    {STR16("Das Gute daran ist, dass es irgendwann vorbei ist."), STR16("The good thing is that it eventually ends.")},
    {STR16("Ich würde eine Pause machen. Die Musik hat sie verdient."), STR16("I'd take a break. The music has earned one.")},
    {STR16("Interessant. Sogar die Stille davor war besser."), STR16("Interesting. Even the silence before it was better.")},
    {STR16("Das klingt nicht unfertig. Das klingt aufgegeben."), STR16("That doesn't sound unfinished. It sounds abandoned.")},
    {STR16("Keine Sorge. Schlimmer wird's statistisch unwahrscheinlich."), STR16("Don't worry. Statistically, getting worse is unlikely.")},
    {STR16("Du machst wirklich weiter. Faszinierend."), STR16("You're really still going. Fascinating.")},
    {STR16("Ich würde helfen. Aber wo soll ich anfangen?"), STR16("I'd help. But where would I even start?")},
    {STR16("Das war vorher schon schlecht. Respekt."), STR16("It was already bad before. Respect.")},
    {STR16("Das war keine Verbesserung. Nur Bewegung."), STR16("That wasn't an improvement. Just movement.")},
    {STR16("Das klingt jetzt anders schlecht."), STR16("Now it sounds differently bad.")},
    {STR16("Niemand hat darum gebeten. Wirklich niemand."), STR16("Nobody asked for that. Absolutely nobody.")},
    {STR16("Zumachen ändert daran leider auch nichts."), STR16("Closing the window unfortunately changes nothing.")},
    {STR16("Ach. Du schon wieder."), STR16("Oh. You again.")},
    {STR16("Na endlich. Genug gelogen."), STR16("Finally. Enough pretending.")},
    {STR16("Das Ergebnis hat Fragen. Ich leider auch."), STR16("The result has questions. So do I.")},
    {STR16("Interessante Entscheidung. Gegen Geschmack."), STR16("Interesting decision. Against taste.")},
    {STR16("Das stolpert, aber wenigstens konsequent."), STR16("It stumbles, but at least consistently.")},
    {STR16("Das klingt teuer. Nicht gut. Nur teuer."), STR16("It sounds expensive. Not good. Just expensive.")},
    {STR16("Vielleicht war Version 17 doch die beste."), STR16("Maybe version 17 really was the best one.")},
    {STR16("Das überzeugt nur den Papierkorb."), STR16("Only the trash can is convinced.")},
    {STR16("Die Pause danach ist bisher das Highlight."), STR16("The silence afterward is the highlight so far.")},
    {STR16("Bitte sag, das war Absicht."), STR16("Please say that was intentional.")},
    {STR16("Das bleibt am besten unter uns."), STR16("This is best kept between us.")},
    {STR16("Ich schaue kurz weg. Mach es rückgängig."), STR16("I'll look away. Undo it.")},
    {STR16("Du hast es nicht verbessert. Nur verändert."), STR16("You didn't improve it. You only changed it.")},
    {STR16("Das ist erstaunlich konsequent daneben."), STR16("That's impressively consistently wrong.")},
    {STR16("Ich wusste nicht, dass man so falsch abbiegen kann."), STR16("I didn't know you could take such a wrong turn.")},
    {STR16("Das ist mutig. Leider nur mutig."), STR16("That's brave. Unfortunately, only brave.")},
    {STR16("Wenn Verwirrung das Ziel war: Volltreffer."), STR16("If confusion was the goal: nailed it.")},
    {STR16("Da ist wirklich nichts versehentlich gut geworden."), STR16("Nothing accidentally became good there.")},
    {STR16("Ich würde das nicht mal dem Papierkorb erklären."), STR16("I wouldn't even explain that to the trash can.")},
    {STR16("Das braucht keine Kritik. Das braucht Zeugen."), STR16("That doesn't need criticism. It needs witnesses.")},
    {STR16("Beeindruckend, wie wenig davon funktioniert."), STR16("Impressive how little of that works.")},
    {STR16("Du hast eine Lösung für ein Problem gebaut, das niemand hatte."), STR16("You built a solution for a problem nobody had.")},
    {STR16("Das klingt nach einer Entscheidung unter Aufsicht."), STR16("That sounds like a decision requiring supervision.")},
    {STR16("Ich vermisse plötzlich die vorherige schlechte Version."), STR16("I suddenly miss the previous bad version.")},
    {STR16("Das war ein Schritt. Richtung ist noch unklar."), STR16("That was a step. Direction remains unclear.")},
    {STR16("So klingt also Selbstsabotage mit Stromanschluss."), STR16("So that's what powered self-sabotage sounds like.")},
    {STR16("Da würde ich jetzt nichts anfassen. Aus Beweisgründen."), STR16("I wouldn't touch that now. For evidence purposes.")},
    {STR16("Das ist kein Charakter. Das ist ein Unfallbericht."), STR16("That's not character. That's an accident report.")},
    {STR16("Wenn das Absicht war, wird es nicht besser."), STR16("If that was intentional, it doesn't make it better.")},
    {STR16("Du hast gerade etwas sehr Besonderes kaputtgemacht: Hoffnung."), STR16("You just broke something very special: hope.")},
    {STR16("Ich glaube, die Idee hat unterwegs gekündigt."), STR16("I think the idea quit halfway through.")},
    {STR16("Das ist erstaunlich viel Aufwand für dieses Ergebnis."), STR16("That's an astonishing amount of effort for this result.")},
    {STR16("Ich höre die Entscheidung. Ich verstehe sie nur nicht."), STR16("I hear the decision. I just don't understand it.")},
    {STR16("Das wirkt wie eine Drohung gegen guten Geschmack."), STR16("That feels like a threat against good taste.")},
    {STR16("Es ist fertig, sobald du aufhörst."), STR16("It's finished as soon as you stop.")},
    {STR16("Das Ergebnis bittet um Anonymität."), STR16("The result is asking to remain anonymous.")},
    {STR16("Du hast Talent. Es versteckt sich nur hervorragend."), STR16("You have talent. It's just hiding extremely well.")},
    {STR16("Ich würde klatschen, aber das wäre irreführend."), STR16("I'd clap, but that would be misleading.")},
    {STR16("Das klingt wie ein Hilferuf mit Lautstärke."), STR16("That sounds like a cry for help with volume.")},
    {STR16("Ich wollte etwas Nettes sagen. Dann kam das hier."), STR16("I wanted to say something nice. Then this happened.")},
    {STR16("Du hast die falsche Entscheidung sehr selbstbewusst getroffen."), STR16("You made the wrong decision with impressive confidence.")},
    {STR16("Das hat jetzt offiziell Aktenzeichen."), STR16("This officially has a case number now.")},
    {STR16("So viel Mut bei so wenig Grund."), STR16("So much courage with so little reason.")},
    {STR16("Ich bin nicht sauer. Nur musikalisch verletzt."), STR16("I'm not angry. Just musically injured.")},
    {STR16("Das ist kein Feinschliff. Das ist Spurensicherung."), STR16("That's not polishing. That's forensic work.")},
    {STR16("Du hast gerade die falsche Stelle perfektioniert."), STR16("You just perfected the wrong thing.")},
    {STR16("Man hört, dass du lange daran gearbeitet hast. Leider."), STR16("You can hear you worked on it for a long time. Unfortunately.")},
    {STR16("Das braucht keinen letzten Schliff. Das braucht einen Neustart."), STR16("That doesn't need a final polish. It needs a restart.")},
    {STR16("Ich kenne schlechtere Entscheidungen. Nicht viele."), STR16("I know worse decisions. Not many.")},
    {STR16("Das ist beeindruckend weit weg von gut."), STR16("That's impressively far from good.")},
    {STR16("Der Mut war da. Der Rest leider nicht."), STR16("The courage was there. Sadly, the rest wasn't.")},
    {STR16("Ich würde das als Phase bezeichnen. Hoffentlich eine kurze."), STR16("I'd call this a phase. Hopefully a short one.")},
    {STR16("Das klingt, als hätte niemand rechtzeitig Nein gesagt."), STR16("That sounds like nobody said no in time.")},
    {STR16("Das ist ein sehr langer Weg zu einer schlechten Idee."), STR16("That's a very long road to a bad idea.")},
    {STR16("Ich sehe, was du wolltest. Das Ergebnis offenbar nicht."), STR16("I see what you wanted. The result apparently doesn't.")},
    {STR16("Da war kurz Hoffnung. Dann kam deine Entscheidung."), STR16("There was hope for a moment. Then came your decision.")},
    {STR16("Ich würde das nicht weiter optimieren. Es könnte überleben."), STR16("I wouldn't optimize that further. It might survive.")},
    {STR16("Das ist kein Problem mehr. Das ist jetzt ein Konzept."), STR16("That's no longer a problem. It's a concept now.")},
    {STR16("Du hast wirklich alles gegeben. Man hört leider was."), STR16("You really gave it everything. Unfortunately, you can hear it.")},
    {STR16("Das ist bemerkenswert. Nicht im guten Sinn."), STR16("That's remarkable. Not in the good way.")},
    {STR16("Ich beantrage fünf Minuten Schweigen."), STR16("I request five minutes of silence.")},
    {STR16("Die gute Nachricht: Es ist nur Audio."), STR16("The good news: it's only audio.")},
    {STR16("Ich glaube, wir sollten so tun, als wäre nichts passiert."), STR16("I think we should pretend nothing happened.")},
    {STR16("Das ist sehr konsequent. Leider falsch."), STR16("That's very consistent. Unfortunately wrong.")},
    {STR16("Ich würde es rückgängig machen, bevor es jemand hört."), STR16("I'd undo it before anyone hears it.")}
}};

constexpr std::size_t kMotivatorCount = kMotivator.size();
constexpr std::size_t kDemotivatorCount = kDemotivator.size();
constexpr std::size_t kPhraseCount = kMotivatorCount + kDemotivatorCount;

} // namespace MotivatoratorPhrases
